name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable]
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo clippy --all-targets
      - run: cargo fmt --check --all
      - run: cargo install wasm-pack
      - run: wasm-pack build --target web --all-targets
      - run: wasm-pack test --node --headless --all-targets

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          milliseconds: 2000
      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"

      - name: Compare Directories
        id: diff
        run: |
          if [ ! -d pkg/ ]; then
            echo "Expected pkg/ directory does not exist.  See status below:"
            ls -la ./
            exit 1
          fi
          if [ "$(git diff --ignore-space-at-eol --text pkg/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff --ignore-space-at-eol --text pkg/
            exit 1
          fi
      - if: ${{ failure() && steps.diff.outcome == 'failure' }}
        name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: pkg
          path: pkg/
